# Generated by Django 3.2.25 on 2025-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100)),
                ('ru_name', models.CharField(max_length=100)),
                ('type', models.CharField(default='глагол', max_length=100)),
                ('total_attempts', models.IntegerField(default=0, verbose_name='количество попыток')),
                ('successful_attempts', models.IntegerField(default=0, verbose_name='количество успешных попыток')),
                ('series', models.IntegerField(default=0, verbose_name='количество успешных попыток подрят')),
            ],
        ),
    ]
