# Generated by Django 3.2.25 on 2026-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100)),
                ('ru_name', models.CharField(max_length=100)),
                ('type', models.CharField(default='proposal', max_length=100)),
                ('total_attempts', models.IntegerField(default=0, verbose_name='количество попыток')),
                ('successful_attempts', models.IntegerField(default=0, verbose_name='количество успешных попыток')),
                ('series', models.IntegerField(default=0, verbose_name='количество успешных попыток подрят')),
            ],
        ),
    ]
